### ISSUE TITLE
Location error

### ISSUE THREAD

**Issue by BSDxxxx** [gera2ld/coc-markmap#11]
Environment:win10 nvim-qt
File: F:\vimwiki\etc.md

1. open nvim -> run `e F:\vimwiki\etc.md` -> run `CocCommand markmap.creat`
```
[coc.nvim] error: UnhandledRejection: EPERM: operation not permitted, open 'C:\WINDOWS\System32\etc.html'
```
The location in error message equals the out of `pwd` when nvim initiate.

~~2. open that file with nvim using `nvim F:\vimwiki\etc.md` -> run `CocCommand markmap.creat`
Succeed~~

**Comment by BSDxxxx** [comment]
I think this plugin suppose to execute the command under the current edit file's path.

**Comment by gera2ld** [comment]
> I think this plugin suppose to execute the command under the current edit file's path.

No, it's not.

I have tested your case with nvim-qt (neovim v0.4.3, Windows 10) but it worked for me.

Could you please check the following?

- neovim version
  - run `:version` in nvim-qt
  - v0.4.3 expected
- coc-markmap version
  - run `:CocList extensions`
  - v0.2.4 expected
- output filename
  - open nvim -> run `:e F:\vimwiki\etc.md`, then
  - `:echo expand('%')`
  - `:echo expand('%<')`

**Comment by BSDxxxx** [comment]
@gera2ld 
- NVIM v0.5.0-416-g2b00d1d09
- coc-markmap v0.2.4
- output filename 1
open nvim -> run `:e F:\vimwiki\etc.md`, then
`:echo expand('%')` ==> `etc.md`
`:echo expand('%<')` ==> `etc`
- output filename 2
CMD: `nvim F:\vimwiki\etc.md`
`:echo expand('%')` ==> `etc.md`
`:echo expand('%<')` ==> `etc`
- output filename 3
Double click `F:\vimwiki\etc.md` in explorer.exe (open with nvim-qt)
`:echo expand('%')` ==> `etc.md`
`:echo expand('%<')` ==> `etc`
- output filename 4
Double click `F:\vimwiki\etc.md` in [double commander](https://doublecmd.sourceforge.io/) (open with nvim-qt)
`:echo expand('%')` ==> `F:\vimwiki\etc.md`
`:echo expand('%<')` ==> `F:\vimwiki\etc`

**Comment by gera2ld** [comment]
coc-markmap is always using the cwd at startup. So if cwd is changed afterwards something wrong will happen. I'll fix it soon.
