### ISSUE TITLE
markmap.create doesn't work

### ISSUE THREAD

**Issue by Rogerskelamen** [gera2ld/coc-markmap#15]
Here I use coc.nvim to install the coc-markmap, but I this message when I run `markmap.create`

```
Error on "runCommand": Cannot read properties of undefined (reading 'watch')
```

What confused me is that everything went well when I run `markmap.watch`.
I'm a new to use this plugin, I wonder what is this 'watch property'?

**Comment by gera2ld** [comment]
Hi, thanks for reaching out.
- `markmap.create` is for creating an HTML file in the same directory as the Markdown file, which is better for sharing.
- `markmap.watch` starts a development server and tracks your cursor, in this case you can easily modify your Markdown file and see the changes.
