### ISSUE TITLE
Results in object object

### ISSUE THREAD

**Issue by ploth** [gera2ld/coc-markmap#6]
This is my markdown file

![image](https://user-images.githubusercontent.com/7986123/79898982-622fdf80-840c-11ea-8a43-b33afa0860f0.png)

This is the resulting html file

![image](https://user-images.githubusercontent.com/7986123/79899046-7a076380-840c-11ea-8787-24dd3d8fe4b4.png)

The script part is aware of my `.md` file content.

**Comment by gera2ld** [comment]
Ah, there are breaking changes in the latest version of markmap-lib.

**Comment by gera2ld** [comment]
fixed in 90fddc14

**Comment by gera2ld** [comment]
You may need to run `:CocUpdate` to force update to the latest version.
