### ISSUE TITLE
Does the coc-markmap plugin support mathjax? 

### ISSUE THREAD

**Issue by hrzyhm** [gera2ld/coc-markmap#7]
the markmap-lib support the mathjax does the coc-markmap plugin support mathjax?

**Comment by gera2ld** [comment]
It's not supported at the moment.

**Comment by gera2ld** [comment]
In the latest version you can enable MathJax explicitly by:

```viml
:CocCommand markmap.create --enable-mathjax
```

**Comment by hrzyhm** [comment]
Yes, great, the plugin is greatly powerful, and the author is more powerful.
