### ISSUE TITLE
Does this plugin support the symbol  "$ "?

### ISSUE THREAD

**Issue by hrzyhm** [gera2ld/coc-markmap#8]
When I typed a mathematical expression `  \( \N_a^{\star} \) `,the plugin worked well. However, When I typed a mathematical expression $ \N_a^{\star} $ ,the plugin couldn't recognize this mathematical expression.
![1](https://user-images.githubusercontent.com/53509306/80559467-2f8b7580-8a10-11ea-851f-1d00ea283548.jpg) It worked well.
![2](https://user-images.githubusercontent.com/53509306/80559553-75e0d480-8a10-11ea-956c-522d7fe272ea.jpg) , the plugin couldn't recognize this mathematical expression.

**Comment by gera2ld** [comment]
It uses [default options](http://docs.mathjax.org/en/latest/options/input/tex.html#option-descriptions) for MathJax, which recognizes only `\(...\)`.

Maybe a configuration should be added for MathJax.

**Comment by gera2ld** [comment]
It's supported in v0.2.3, see https://github.com/gera2ld/coc-markmap#cocconfig

**Comment by hrzyhm** [comment]
Thank You, it works well.
