### ISSUE TITLE
Does the plugin support the AMSmath environments (\begin{aligned}....\end{aligned})?

### ISSUE THREAD

**Issue by hrzyhm** [gera2ld/coc-markmap#9]
When I typed the sentences "- $$\begin{aligned}\sigma \\ \delta\end{aligned}$$"，the result  was
![2](https://user-images.githubusercontent.com/53509306/80803422-d0328e80-8be4-11ea-8726-68cde5d9eef0.jpg).
The symbols "\ \\" did not work.

**Comment by hrzyhm** [comment]
The right result is 
![1](https://user-images.githubusercontent.com/53509306/80803686-a4fc6f00-8be5-11ea-8f32-bde56420573f.jpg)

**Comment by hrzyhm** [comment]
![3](https://user-images.githubusercontent.com/53509306/80803740-cd846900-8be5-11ea-91f3-83418797e068.jpg)

**Comment by gera2ld** [comment]
The backslash needs to be escaped in Markdown. Either of the following works:

```
- $$\begin{aligned}\sigma \\\\ \delta\end{aligned}$$
- `$$\begin{aligned}\sigma \\ \delta\end{aligned}$$`
```

See also https://github.com/gera2ld/markmap-lib/issues/9#issuecomment-617031900 .
